name: Build Android 64-bit

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Android64
          sdk: given

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: FPS-Unlocker-Android64
          path: ${{ steps.build.outputs.build-output }}/*.geode
